fix linker error on build
Switch from system-uuid to uuid package.
system-uuid causes the following error:
  error: undefined reference to 'uuid_generate_random'

Moving to the uuid package fixes this.